version: '3' # composeファイルのバージョン

services:
  # サービス名
  app:
    # ビルドに使うDockerfileの場所
    build: ./docker/go
    # コンテナの永続化
    tty: true
    # 外部に公開するポートを指定
    ports:
      - 8080:8080
    # マウントディレクトリ
    volumes:
      - .:/go/src/app
    # docker-compose run実行時に実行される
    command: go run cmd/main.go
